<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.7</version>
    </parent>
    <artifactId>dows-exam</artifactId>
    <groupId>org.dows.cloud</groupId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <spring-ai.version>1.0.1</spring-ai.version>
        <spring-boot.version>3.5.7</spring-boot.version>
        <spring-doc.version>2.8.14</spring-doc.version>
        <fastjson2.version>2.0.58</fastjson2.version>

        <rade.version>1.0.251113-SNAPSHOT</rade.version>
        <disruptor.version>4.0.0</disruptor.version>
        <h2.version>2.2.224</h2.version>
        <dotenv-java.version>3.2.0</dotenv-java.version>
        <mybatis-flex.version>1.11.1</mybatis-flex.version>
    </properties>

    <modules>
        <module>exam-api</module>
        <module>exam-feign</module>
        <module>exam-app</module>
        <module>exam-boot</module>
        <module>exam-core</module>
        <module>exam-rest</module>
        <module>exam-service</module>
        <module>exam-repository</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-feign</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-app</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-boot</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-rest</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-service</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>exam-repository</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>rade-crud</artifactId>
                <version>${rade.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cdimascio</groupId>
                <artifactId>dotenv-java</artifactId>
                <version>${dotenv-java.version}</version>
            </dependency>

            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lmax</groupId>
                <artifactId>disruptor</artifactId>
                <version>${disruptor.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${spring-doc.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

